# Generated by Django 5.0.1 on 2024-01-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_theaters_screen_movie_screens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('top', 'Top'), ('latest', 'Latest')], default='latest', max_length=50),
        ),
    ]
